CREATE TABLE IF NOT EXISTS candidate_evaluations (
  id SERIAL PRIMARY KEY,
  candidate_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  job_id INTEGER REFERENCES jobs(id) ON DELETE CASCADE,
  score NUMERIC DEFAULT 0,
  notes TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);