INSERT INTO users (
    name,
    email,
    password,
    role,
    country,
    city,
    professional_title,
    professional_summary,
    years_of_experience,
    skills,
    profile_image,
    is_email_verified,
    created_at,
    updated_at
)
VALUES
(
    'Adebayo Ogunleye',
    'adebayo@goproafrica.com',
    '$2b$10$8U0VY9K7M9qW0K9Q3M3zUeY8v8L6Qm5wY6mQx0uN7YkP4Q6rYJr6C',
    'recruiter',
    'Nigeria',
    'Lagos',
    'Senior Technical Recruiter',
    'Experienced recruiter focused on engineering talent acquisition and African tech workforce development.',
    8,
    'Technical Recruitment, Talent Acquisition, HR Strategy, Interviewing, Career Coaching',
    '/images/avatar.jpg',
    true,
    NOW(),
    NOW()
),
(
    'Grace Mensah',
    'grace@goproafrica.com',
    '$2b$10$8U0VY9K7M9qW0K9Q3M3zUeY8v8L6Qm5wY6mQx0uN7YkP4Q6rYJr6C',
    'recruiter',
    'Ghana',
    'Accra',
    'Talent Development Recruiter',
    'Supports candidate career growth and employer matchmaking across Africa.',
    6,
    'Talent Management, Candidate Evaluation, Career Development, HR Operations',
    '/images/avatar.jpg',
    true,
    NOW(),
    NOW()
),
(
    'Fatou Sarr',
    'fatou@goproafrica.com',
    '$2b$10$8U0VY9K7M9qW0K9Q3M3zUeY8v8L6Qm5wY6mQx0uN7YkP4Q6rYJr6C',
    'recruiter',
    'Senegal',
    'Dakar',
    'International Recruitment Specialist',
    'Focused on connecting African professionals with international opportunities.',
    7,
    'Global Recruitment, Candidate Screening, Workforce Mobility, Employer Relations',
    '/images/avatar.jpg',
    true,
    NOW(),
    NOW()
),
(
    'Linda Mwangi',
    'linda@goproafrica.com',
    '$2b$10$8U0VY9K7M9qW0K9Q3M3zUeY8v8L6Qm5wY6mQx0uN7YkP4Q6rYJr6C',
    'recruiter',
    'Kenya',
    'Nairobi',
    'Digital Talent Recruiter',
    'Specialized in sourcing and mentoring software engineering and AI talent.',
    5,
    'Recruitment, AI Talent, Technical Screening, Employer Matching',
    '/images/avatar.jpg',
    true,
    NOW(),
    NOW()
),
(
    'Moussa Diallo',
    'moussa@goproafrica.com',
    '$2b$10$8U0VY9K7M9qW0K9Q3M3zUeY8v8L6Qm5wY6mQx0uN7YkP4Q6rYJr6C',
    'recruiter',
    'The Gambia',
    'Banjul',
    'Regional Talent Coordinator',
    'Coordinates recruitment pipelines and talent readiness programs across West Africa.',
    4,
    'Candidate Coordination, Recruitment Pipelines, Talent Support, Career Guidance',
    '/images/avatar.jpg',
    true,
    NOW(),
    NOW()
);